---
- name: install redis
  hosts: all
  user: root
  roles:
    - common

- name: configure redis-master
  hosts: redis-master
  user: root
  roles:
    - redis-master

- name: configure redis-slave
  hosts: redis-slave
  user: root
  roles:
    - redis-slave
